# Generated by Django 2.2.11 on 2021-07-04 11:38

from django.db import migrations, models
import me.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('otp', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('thumbnail', models.TextField()),
                ('title', models.TextField()),
                ('caption', models.TextField()),
                ('post', models.TextField()),
                ('post_json', models.TextField()),
                ('tags', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=me.models.image_name)),
                ('name', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('otp', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('thumbnail', models.TextField()),
                ('title', models.TextField()),
                ('caption', models.TextField()),
                ('post', models.TextField()),
                ('post_json', models.TextField()),
                ('tags', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
