# Generated by Django 2.2.11 on 2021-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
